"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['widget.py']
DATA_FILES = ["config.py","images.py","listwidget.py","pwidget.py","QtSingleApplication.py","utiltool.py"]
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'app.ico',
}

setup(
    name="kontakt-tool",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
